package com.swinburne.timur.assignment3task2;

import android.support.v7.app.AppCompatActivity;
import android.os.Bundle;

/**
 * Autogenerated stub
 */
public class ProfileView extends AppCompatActivity {

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_profile_view);
    }
}
